### ISSUE TITLE
32bit problem

### ISSUE THREAD

**Issue by Deshdeepak1** [niklasmohrin/clircle#2]
Not installing on 32 bit systems,  while installing the newest version of bat.
https://github.com/termux/termux-packages/runs/1443682248?check_suite_focus=true#step:4:768

**Comment by niklasmohrin** [comment]
Hey @Deshdeepak1, thank you for sharing the build output! I was able to reproduce the error on my local machine, using the `i686-linux-android` build target like in your build. The error is weird, because I made sure to use the platform independent types directly from `libc`, but Android seems to behave differently. Do you by chance know anything about how this works there, to speed up the fix of this bug?

**Comment by niklasmohrin** [comment]
Also, I talked to the `bat` maintainer and the feature will be reverted for now. I will make sure to add tests for your use-case once this is fixed and goes live again.

**Comment by niklasmohrin** [comment]
@Deshdeepak1 I looked into your project a bit and saw that you blacklisted `bat` for arm as well. This surprised me, because `bat` is running CI against both the `arm-unknown-linux-gnueabihf` and `aarch64-unknown-linux-gnu` target.  Are there more build targets affected that need fixing, or should this be a fix tinkered around the android target?

**Comment by niklasmohrin** [comment]
Okay, I fixed everything that is known so far and packaged a new release that supports more platforms! I am opening a PR to `bat` next.

**Comment by Deshdeepak1** [comment]
> @Deshdeepak1 I looked into your project a bit and saw that you blacklisted `bat` for arm as well. This surprised me, because `bat` is running CI against both the `arm-unknown-linux-gnueabihf` and `aarch64-unknown-linux-gnu` target. Are there more build targets affected that need fixing, or should this be a fix tinkered around the android target?

Well since the build on i686 failed, it terminated builds for different arch,  but someone in our community did try to build in his arm phone and error was same. 
![IMG_20201125_105805_814](https://user-images.githubusercontent.com/36617998/100187049-42feb080-2f0d-11eb-9ff2-e417050433f5.jpg)
After blacklisting i686 and arm, build was successfull, so 64bits targets were building successfully.
After the new bat ( after reverting) build is succesfull for all targets. https://github.com/termux/termux-packages/pull/6075/checks?check_run_id=1451578313 .  
Will check  again after your new PR is merged.

**Comment by RupankarGhosh** [comment]
That was me who tried to build. The latest version was failing because of `clircle`. But I checked the v0.16.0 and succeed in building without any error. I checked with another phone later with aarch64 and there the latest was also building without any problem. So it's a problem in arm architecture in `clircle` crate.

**Comment by niklasmohrin** [comment]
@Deshdeepak1 @RupankarGhosh I added even more platforms to CI, please check that all the platforms you are building for are among them. It will take slightly more time before `bat` comes back with this enabled though.

**Comment by niklasmohrin** [comment]
@Deshdeepak1 @RupankarGhosh bat v0.18 is out with the current version of this crate where this should all be fixed
